### ISSUE TITLE
Description of src/main/js incomplete in Part 1

### ISSUE THREAD

**Issue by Michael960** [spring-guides/tut-react-and-spring-data-rest#109]
I tried to follow the tutorial from scratch (using STS 4). Until the first run ("Touring your REST service") there were no problems. But at the second run (at the end of "Diving into React") I ran into the following non-self-explaining error:
```
[ERROR] Failed to execute goal com.github.eirslett:frontend-maven-plugin:1.6:webpack (webpack build) on project react-and-spring-data-rest-basic: Failed to run task: 'webpack.js ' failed. org.apache.commons.exec.ExecuteException: Process exited with an error: 2 (Exit value: 2) -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException
```

After investigating the differences between my source and the GIT source using KDiff3 for four hours, I found out that in my source, the following files were missing as the tutorial did not instruct me to create then (and also did not explain them):
- src/main/js/client.js
- src/main/js/api/uriListConverter.js
- src/main/js/api/uriTemplateInterceptor.js

After copying them from the GIT source, my source built successfully.

I think it would be helpful for many people to complete this in the tutorial as it is quite frustrating if you try to follow a tutorial and get some errors that you don't manage to get resolved. And I guess that most beginners are not able to resolve this one themselves.

**Comment by Michael960** [comment]
main.css is also not described. But this does not run into a build error, it just makes the output look less beautiful. But I think that, for completeness, this should also be described.

**Comment by gregturn** [comment]
* There is a section right below `const client = require('./client');` that says "client is custom code that configures rest.js to support..."

I originally left that out on purpose, since it was specific to the rest JS toolkit for doing REST calls, and not critical to what you did. There is a hyperlink to view the file. I had thought it would slow down the tutorial. If you think this needs to be inlined, we can entertain that.

Being part of `client.js`, I also left out the UriList and UriTemplate handler code for the same reason. If you decided, today, to use restangular, you could easily read this tutorial and plug that in.

Perhaps if I reworded the tutorial to emphasize that point would be better than dragging in code that wires a now defunct JS library?
