### ISSUE TITLE
Spring is appending a second link under "_links" which seems to cause confusion

### ISSUE THREAD

**Issue by tur-ing** [spring-guides/tut-react-and-spring-data-rest#13]
How can I get rid of that `employee` under `_links`?

<img width="660" alt="bildschirmfoto 2016-02-24 um 13 57 58" src="https://cloud.githubusercontent.com/assets/15199933/13286012/d6489ff8-dafe-11e5-93b4-d5ee766e0f04.png">

**Comment by dsyer** [comment]
I'm not quite sure which link you don't like (or why). Can you be a bit more explicit?

**Comment by gregturn** [comment]
The "employee" link is used to show URI templates against the resource. For example, later in the tutorial when paging is turned on, those parameters are shown on the "employee" link. 

Because the "self" link is free of context, it does NOT show that. 

In both situations we don't eliminate links. That doesn't make any sense. The idea of links is to give API consumers options.

**Comment by tur-ing** [comment]
Yes, of course: I get the following error, which I think might appear because of this extra link ("employee":{"href":"..."}). This link is not appearing in Gregs tutorial ....

**Comment by gregturn** [comment]
"employee" is below _links. This error message indicates the attribute above it is undefined.

Which section are you running?

**Comment by tur-ing** [comment]
The "hypermedia" section.

**Comment by tur-ing** [comment]
Now I know the reason why I can not work with the employees. I am not able to fetch the /api/profile/employees as schema+json. I have to fix this first.

**Comment by gregturn** [comment]
I was about to say, it works for me.

**Comment by gregturn** [comment]
So if it's an issue with Zuul, can we close this ticket?

**Comment by tur-ing** [comment]
Yes thank you!
