### ISSUE TITLE
Use then instead of done for rest.js callbacks

### ISSUE THREAD

**Issue by chrylis** [spring-guides/tut-react-and-spring-data-rest#29]
As of version 2.0.0, it appears that the Promise returned by the rest.js `client` call no longer defines a `done()` method, instead relying on the first argument to `then()` (more minimally conforming to A+). The AJAX calls seem to work correctly when `done` is trivially replaced with `then`.

**Comment by bolkin** [comment]
I had to set explicit version of rest to 1.3.2 because of the same problem. Also these dependencies are missing from package.json?

diff --git a/security/package.json b/security/package.json
index 898c9a9..7fa50fd 100644
--- a/security/package.json
+++ b/security/package.json
@@ -24,9 +24,11 @@
     "babel-loader": "^5.3.2",
     "react": "^15.3.2",
     "react-dom": "^15.3.2",
+    "rest": "1.3.2",
     "sockjs-client": "^1.0.3",
     "stompjs": "^2.3.3",
-    "webpack": "^1.12.2"
+    "webpack": "^1.12.2",
+    "when": "^3.7.7"
   },
   "scripts": {
     "watch": "webpack --watch -d"

**Comment by gregturn** [comment]
Given rest.js has been archived, there is little value in quibbling over the version used.
