### ISSUE TITLE
Sample Java code can include import statements

### ISSUE THREAD

**Issue by alanfraneo** [spring-guides/tut-react-and-spring-data-rest#32]
I was looking at this guide (https://spring.io/guides/tutorials/react-and-spring-data-rest/) and followed it by copy pasting the code into IntelliJ, however when IntelliJ tried to auto imported the dependencies, It showed multiple dependencies for @Id and @Entity Annotations. It would be nice to include those import statements in the sample code itself, instead of letting a beginner guess.

**Comment by gregturn** [comment]
Bottom line: @Id and @Entity are JPA annotations, so that's what you need to use. If you read the source, you'd find it there as well.

I'm not sure there is a huge benefit in slowing down the tutorial to make it a JPA tutorial as well.

https://github.com/spring-guides/tut-react-and-spring-data-rest/blob/master/basic/src/main/java/com/greglturnquist/payroll/Employee.java#L20
