### ISSUE TITLE
When I use eclipse, import existing maven projects, I got error.

### ISSUE THREAD

**Issue by oldfeel** [spring-guides/tut-react-and-spring-data-rest#4]
````
Plugin execution not covered by lifecycle configuration: com.github.eirslett:frontend-maven-plugin:0.0.24:webpack (execution: webpack build, phase: generate-resources)
````
![2016-01-01 09-35-50](https://cloud.githubusercontent.com/assets/1726280/12069450/7bb108ea-b06b-11e5-8d05-471126a30cbc.png)

**Comment by rfkarlin** [comment]
I get this same error.  Can anyone suggest a fix?

**Comment by gregturn** [comment]
First and foremost, does it work on the CLI with maven on your box? If so, then can we confine it to a plugin issue with Eclipse? Might illuminate opening an issue with Eclipse.

**Comment by rfkarlin** [comment]
Using ./mvnw spring-boot:run I can run the app and use curl to call the api methods but if I try to browse to localhost:8080 I get a 404 and no error on the command line.

I have to admit that I am new to all of this (or I should say returning to some front end development after many years away from it.

Thanks,

—Robin
Robin F Karlin
Principal Systems Software Engineer
Identity Services
Carnegie Mellon University
5000 Forbes Avenue
Pittsburgh, PA 15213-3890
Office: 412-268-9046




On Jan 27, 2016, at 12:11 PM, Greg Turnquist <notifications@github.com<mailto:notifications@github.com>> wrote:


First and foremost, does it work on the CLI with maven on your box? If so, then can we confine it to a plugin issue with Eclipse? Might illuminate opening an issue with Eclipse.

**Comment by dsyer** [comment]
Works for me on the command line.

As far as Eclipse goes there's probably no point trying to raise issues because it's clearly a maven plugin causing the error. You should find there is a "Quick Fix" for it in Eclipse, and one of the options is to simply ignore the error. We could update the tutorial to make it clear to Eclipse users that they might have to do this.

**Comment by rfkarlin** [comment]
Hi,

I got further with the GUI after creating env vars for JAVA_HOME and M2_HOME.

However now I get this error:


  1.
Request URL:
http://localhost:8080/bower_components/react/JSXTransformer.js
  2.
Request Method:
GET
  3.
Status Code:
404 Not Found
  4.
Remote Address:
[::1]:8080


Any help would be appreciated.

Thanks,

—Robin

Robin F Karlin
Principal Systems Software Engineer
Identity Services
Carnegie Mellon University
5000 Forbes Avenue
Pittsburgh, PA 15213-3890
Office: 412-268-9046




On Jan 27, 2016, at 12:11 PM, Greg Turnquist <notifications@github.com<mailto:notifications@github.com>> wrote:


First and foremost, does it work on the CLI with maven on your box? If so, then can we confine it to a plugin issue with Eclipse? Might illuminate opening an issue with Eclipse.

**Comment by gregturn** [comment]
Ever since https://github.com/spring-guides/tut-react-and-spring-data-rest/commit/bf813e2a5744364d409d78a93c9f6aca8a71a41a, we no longer use bower, so you won't find any components there.

Also, there are several commits before that one, where all the code was migrated to ES6 using babel.js, so we no longer need the JSX Transformer. You may want to check that you have the latest copy of the code.

**Comment by rfkarlin** [comment]
Odd.  I got the code from the DOWNLOAD ZIP button at this URL:

https://spring.io/guides/tutorials/react-and-spring-data-rest/

—Robin
Robin F Karlin
Principal Systems Software Engineer
Identity Services
Carnegie Mellon University
5000 Forbes Avenue
Pittsburgh, PA 15213-3890
Office: 412-268-9046




On Jan 27, 2016, at 2:29 PM, Greg Turnquist <notifications@github.com<mailto:notifications@github.com>> wrote:


Ever since bf813e2<https://github.com/spring-guides/tut-react-and-spring-data-rest/commit/bf813e2a5744364d409d78a93c9f6aca8a71a41a>, we no longer use bower, so you won't find any components there.

Also, there are several commits before that one, where all the code was migrated to ES6 using babel.js, so we no longer need the JSX Transformer. You may want to check that you have the latest copy of the code.

**Comment by gregturn** [comment]
In that case, you have a snapshot instead of a git clone, meaning you can't keep up with the changes.

**Comment by rfkarlin** [comment]
ok.  I’ll do the clone.  But I just got that code at 11 or so this morning so I would have thought it would work for at least a few hours!
Robin F Karlin
Principal Systems Software Engineer
Identity Services
Carnegie Mellon University
5000 Forbes Avenue
Pittsburgh, PA 15213-3890
Office: 412-268-9046



On Jan 27, 2016, at 2:34 PM, Greg Turnquist <notifications@github.com<mailto:notifications@github.com>> wrote:


In that case, you have a snapshot instead of a git clone, meaning you can't keep up with the changes.

**Comment by gregturn** [comment]
o_0

Not sure what to tell you. I grabbed a snapshot five minutes ago, and didn't see any bower artifacts. The commits I cited were done in early December. Happy cloning.

**Comment by rfkarlin** [comment]
That fixed the problem.  Thanks for the help and sorry to bother you.  Now to see if I can figure out any of this code!


Robin F Karlin
Principal Systems Software Engineer
Identity Services
Carnegie Mellon University
5000 Forbes Avenue
Pittsburgh, PA 15213-3890
Office: 412-268-9046



On Jan 27, 2016, at 2:39 PM, Greg Turnquist <notifications@github.com<mailto:notifications@github.com>> wrote:


o_0

Not sure what to tell you. I grabbed a snapshot five minutes ago, and didn't see any bower artifacts. The commits I cited were done in early December. Happy cloning.
