### ISSUE TITLE
Entrypoint main() must be under the same package with controller?

### ISSUE THREAD

**Issue by visaxin** [spring-guides/tut-react-and-spring-data-rest#45]
In basic part, I put main() in A package, HomeController in B package.  
Change Employee to Account

After start app, curl localhost:8080/api,
below code // start to //end is none, which means DatabaseLoader didn't load the pre-data.

```
{
  "_links" : {
// start
    "accounts" : {
      "href" : "http://localhost:8080/api/accounts"
    },
// end
    "profile" : {
      "href" : "http://localhost:8080/api/profile"
    }
  }
}
```

**Comment by gregturn** [comment]
By default, the package where Spring Boot scans for beans and Spring Data repositories is the one you put @SpringBootApplication in, and all of its subpackages. If `A` and `B` are sibling packages, that's why nothing is getting picked up.

You can easily override this using the annotations `scanBasePackageClasses` parameter. Simply provide an array of a top-level class from package A and from package B, and it will scan both, like this:

```
import A.SomeClassInA;
import B.SomeClassInB;

@SpringBootApplication(scanBasePackageClasses = {SomeClassInA.class, SomeClassInB.class})
public class MyApp {
 ...
}
```

**Comment by gregturn** [comment]
Seeing no more followup, I'm closing this issue.
