### ISSUE TITLE
Uncaught TypeError: client(...).done is not a function

### ISSUE THREAD

**Issue by hahahaha123567** [spring-guides/tut-react-and-spring-data-rest#78]
It seems like chrome didn't recognize done() in rest.js.
I guess there is something wrong about my frontend compiling configuration, but package.json and .babelrc are as same as the example code.

**Comment by himanshusehgal** [comment]
Hi,
May i know which lib version are you talking about, that fixed this problem ?
Thanks !

**Comment by havvyliu** [comment]
Rest, react and react-dom have to be same version as what specified in package.json

**Comment by hidraulicChicken** [comment]
Well, I have almost the same error, but with follow().then().done() It throws typeError too. Versions are the same for react and react-dom. Any ideas?

**Comment by hahahaha123567** [comment]
@hidraulicChicken replace done() with then(). then() is in specification in JS, while done() is in rest.js and I don't know why it doesn't work

**Comment by hidraulicChicken** [comment]
@hahahaha123567 does that mean that the rest.js version number should be the same as the react ones?

**Comment by programmerKANG** [comment]
if you wanna use rest module with higher version
use then(...) instead of done(...)

check Usage in
https://www.npmjs.com/package/rest

**Comment by CloakingOcean** [comment]
For anyone reading this down the road, I believe the original error is due to not having the [client.js](https://github.com/spring-guides/tut-react-and-spring-data-rest/blob/master/hypermedia/src/main/js/client.js) and [follow.js](https://github.com/spring-guides/tut-react-and-spring-data-rest/blob/master/hypermedia/src/main/js/follow.js) file in your js folder. As well, it's likely you don't have the [uriListConverter](https://github.com/spring-guides/tut-react-and-spring-data-rest/blob/master/hypermedia/src/main/js/api/uriListConverter.js) and [uriTemplateInterceptor](https://github.com/spring-guides/tut-react-and-spring-data-rest/blob/master/hypermedia/src/main/js/api/uriTemplateInterceptor.js) in your js.api folder. This is due to the tutorial not explicitly showing you the code for those files or that you're even supposed to make them at all. I had to do a lot of cross-referencing of the repository to be able to find the files I needed that were mentioned in the tutorial.

**Comment by gregturn** [comment]
rest.js as a project has been archived, so there is little value in upgrading it past the current version.
